library(xaringanthemer)
#background_color = "#ddddbb"
background_color = "#ccdddd"
inverse_background_color = "#272822"
inverse_text_color = "#d6d6d6"
write_xaringan_theme(text_color = "#000",
                     header_color = "#308bd2",
                     background_color = background_color,
                     inverse_background_color = inverse_background_color,
                     #link_color = "rgb(249, 38, 114)",
                     link_color = "#23cc00",
                     text_bold_color = NA,
                     text_slide_number_color = inverse_background_color,
                     padding = "1em 4em 1em 4em",
                     background_image = NA,
                     background_size = NA,
                     background_position = NA,
                     code_highlight_color = "rgba(255,255,0,0.5)",
                     code_inline_color = "#ff6900",
                     code_inline_background_color = NA,
                     code_inline_font_size = "1em",
                     inverse_text_color = inverse_text_color,
                     inverse_text_shadow = FALSE,
                     inverse_header_color = "#50aaee",
                     title_slide_text_color = inverse_text_color,
                     title_slide_background_color = inverse_background_color,
                     title_slide_background_image = NA,
                     title_slide_background_size = NA,
                     title_slide_background_position = NA,
                     footnote_color = NA,
                     footnote_font_size = "0.9em",
                     footnote_position_bottom = "3em",
                     left_column_subtle_color = "#777",
                     left_column_selected_color = "#000",
                     blockquote_left_border_color = "lightgray",
                     table_border_color = "#666",
                     table_row_border_color = "#ddd",
                     table_row_even_background_color = "#eee",
                     text_font_size = "25px",
                     header_h1_font_size = "55px",
                     header_h2_font_size = "45px",
                     header_h3_font_size = "35px",
                     text_slide_number_font_size = "0.7em",
                     #text_font_google = NULL,
                     text_font_google = google_font("Montserrat", "300", "300i"),
                     #text_font_family = "'Droid Sans'",
                     text_font_weight = "normal",
                     #text_font_url = "https://fonts.googleapis.com/css?family=Droid+Sans:400,700,400italic",
                     text_font_family_fallback = "'Palatino Linotype', 'Book Antiqua', Palatino, 'Microsoft YaHei', 'Songti SC'",
                     text_font_base = "sans",
                     header_font_google = NULL,
                     header_font_family = "'Yanone Kaffeesatz'",
                     header_font_weight = "normal",
                     header_font_url = "https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz",
                     code_font_google = NULL,
                     code_font_family = "'Source Code Pro'",
                     code_font_size = "0.7em",
                     code_font_url = "https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700",
                     code_font_family_fallback = "'Lucida Console', Monaco",
                     extra_css = list(
                                      ".small" = list ("font-size" = "90%"),
                                      ".large" = list ("font-size" = "130%"),
                                      ".bold" = list ("font-weight" = "bold"),
                                      ".fonthuge" = list ("font-size" = "500%",
                                                          "color" = "#FFCC00",
                                                          "line-height" = "100px"),
                                      ".fontBIG" = list ("font-size" = "300%",
                                                          "color" = "#FFCC00",
                                                          "line-height" = "80px"),
                                      ".box-right" = list("height" = "300px",
                                                          "width" = "300px",
                                                          "position" = "absolute",
                                                          "top" = "10%",
                                                          "left" = "65%"),
                                      ".col-right-mid" = list("height" = "100%",
                                                              "width" = "50%",
                                                              "position" = "absolute",
                                                              "top" = "33%",
                                                              "left" = "50%"),
                                      ".box-bottom" = list("height" = "100px",
                                                           "width" = "70%",
                                                           "font-size" = "90%",
                                                           "position" = "absolute",
                                                           "top" = "85%",
                                                           "left" = "15%"),
                                      ".left-column" = list (
                                                             "width" = "50%",
                                                             "float" = "left"),
                                      ".right-column" = list (
                                                              "width" = "50%",
                                                              "float" = "right",
                                                              "padding-top" = "0em")
                                      ),
                     extra_fonts = NULL,
                     outfile = "xaringan-themer.css")
